-- 1. Organization
CREATE TABLE ORGANIZATION (
  Org_id INT AUTO_INCREMENT PRIMARY KEY,
  Org_Name VARCHAR(255) NOT NULL,
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Roles
CREATE TABLE ROLES (
  Role_id INT PRIMARY KEY,
  Role_Name VARCHAR(100) NOT NULL
);

-- 3. Resource Category
CREATE TABLE RESOURCE_CATEGORY (
  Cat_id INT AUTO_INCREMENT PRIMARY KEY,
  Org_id INT NOT NULL,
  Category_Name VARCHAR(100) NOT NULL,
  Max_Duration_Minutes INT DEFAULT NULL,
  FOREIGN KEY (Org_id) REFERENCES ORGANIZATION(Org_id) ON DELETE CASCADE
);

-- 4. Users
CREATE TABLE USERS (
  U_id INT AUTO_INCREMENT PRIMARY KEY,
  Org_id INT NOT NULL,
  Role_id INT DEFAULT NULL,
  is_active TINYINT(1) DEFAULT 1,
  Name VARCHAR(100) NOT NULL,
  Email VARCHAR(150) NOT NULL UNIQUE,
  Password VARCHAR(255) NOT NULL,
  FOREIGN KEY (Org_id) REFERENCES ORGANIZATION(Org_id) ON DELETE CASCADE,
  FOREIGN KEY (Role_id) REFERENCES ROLES(Role_id) ON DELETE SET NULL
);

-- 5. Resources
CREATE TABLE RESOURCES (
  Res_id INT AUTO_INCREMENT PRIMARY KEY,
  Org_id INT NOT NULL,
  Cat_id INT DEFAULT NULL,
  Res_Name VARCHAR(100) NOT NULL,
  Status VARCHAR(50) DEFAULT 'Available',
  FOREIGN KEY (Cat_id) REFERENCES RESOURCE_CATEGORY(Cat_id) ON DELETE RESTRICT,
  FOREIGN KEY (Org_id) REFERENCES ORGANIZATION(Org_id) ON DELETE CASCADE
);

-- 6. Bookings
CREATE TABLE BOOKINGS (
  B_id INT AUTO_INCREMENT PRIMARY KEY,
  Org_id INT NOT NULL,
  U_id INT NOT NULL,
  Res_id INT NOT NULL,
  Status VARCHAR(50) DEFAULT 'Confirmed',
  Start_Time DATETIME NOT NULL,
  End_Time DATETIME NOT NULL,
  FOREIGN KEY (Org_id) REFERENCES ORGANIZATION(Org_id) ON DELETE CASCADE,
  FOREIGN KEY (U_id) REFERENCES USERS(U_id) ON DELETE CASCADE,
  FOREIGN KEY (Res_id) REFERENCES RESOURCES(Res_id) ON DELETE CASCADE
);

-- 7. Audit Logs
CREATE TABLE AUDIT_LOGS (
  Log_id INT AUTO_INCREMENT PRIMARY KEY,
  Org_id INT NOT NULL,
  U_id INT DEFAULT NULL,
  Action TEXT NOT NULL,
  Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Org_id) REFERENCES ORGANIZATION(Org_id) ON DELETE CASCADE,
  FOREIGN KEY (U_id) REFERENCES USERS(U_id) ON DELETE SET NULL
);

CREATE INDEX idx_user_email ON USERS(Email);
CREATE INDEX idx_resource_status ON RESOURCES(Status);
CREATE INDEX idx_booking_time ON BOOKINGS(Start_Time, End_Time);

INSERT INTO ROLES (Role_id, Role_Name) VALUES (1, 'Admin'), (2, 'Employee');